use_default_settings: true

general:
  instance_name: "Kami Search"
  
brand:
  new_issue_url: ""
  docs_url: ""
  public_instances: ""
  wiki_url: ""
  issue_url: ""

server:
  secret_key: "__REPLACE_THIS__"  # Railway will use env var
  limiter: true
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0:8080"

ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: auto
  custom_css: "/static/themes/simple/css/custom.css"

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: "en"
  formats:
    - html
    - json

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'

engines:
  - name: duckduckgo
    disabled: false
    weight: 1.5
  - name: brave
    disabled: false
    weight: 1.5
  - name: wikipedia
    disabled: false
  - name: github
    disabled: false
  - name: stackoverflow
    disabled: false
  - name: reddit
    disabled: false
